import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Site Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="w-full max-w-[1020px] m-auto p-4">
      <nav className="flex items-center justify-between py-4">
        <a href="/" className="text-2xl font-bold p-2 m-2">
          Travel Site Admin
        </a>
         <a href="/destinations" className="text-2xl font-bold p-2 m-2">
          Destinations
        </a>
        <a href="/destinations/new" className="text-2xl font-bold p-2 m-2">
          Add Destination
        </a>



      </nav>

        {children}
        </div>
        </body>
    </html>
  );
}
